name: '🔎 Python Tests'

on:
  push:
  pull_request:
    types: [opened, reopened, edited, ready_for_review, synchronize]

concurrency:
  group: ci-tests-${{ github.ref }}-pytest
  cancel-in-progress: true

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # Unit tests
      - name: Unit Tests (Coverage)
        if: matrix.python-version == '3.10'
        run: python -m pytest test
